### ISSUE TITLE
Player data required

### ISSUE THREAD

**Issue by Haberno** [Im-Stevemmmmm/tbhs-api#1]
__Offensive Stats__                                                                                
- Kills                                                                                                                                                        
- Assists 
- Sword Hits
- Arrows Shot
- Arrows Hit
- Damage Dealt
- Melee Damage Dealt 
- Bow Damage Dealt 
- Highest Streak 

__Defensive Stats__ 
- Deaths 
- Damage Taken
- Melee Damage Taken
- Bow Damage Taken

__Performance Stats__ 
- XP 
- XP/hour
- Gold Earned 
- Gold/hour
- K/D
- K+A/D
- K+A/hour
- damage dealt/taken
- Bow accuracy
- Contracts Started 
- Contracts Completed

__Perks/Mystic Stats__ 
- Golden Apples Eaten
- Golden Heads Eaten
- Lava Buckets Emptied
- Fishing Rods Launched
- Soups Drank
- T1 Mystic Enchanted
- T2 Mystic Enchanted
- T3 Mystic Enchanted
- Dark Pants Enchanted

__Miscellaneous Stats__ 
- Playtime
- Left Clicks
- Diamond Items Purchased
- Chat messages
- Blocks Placed
- Blocks Broken
- Jumps into Pit
- Launcher Launches
- Daily Trade Limits
- Gold Trade Limits
- Genesis Points

__Farming Stats__
- Wheat Farmed
- Fished Anything
- Fished Fish
- Fish Sold
- Hay Bales Sold
- King's Quest Completed
- Sewer Treasures Found
- Night Quests Completed

__Prestige Stats__
- Prestige
- Current Renown
- Lifetime Renown
- Renown Shop Completion

All stats needed and packaged in set categories :).

**Comment by estebangarcia21** [comment]
Got everything down. Thanks.
